/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Login;
import javax.swing.JOptionPane;

/**
 *
 * @author Moon
 */
public class FRM_Login extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Login
     */
    Controlador_FRM_Login controladorLogin;
    
    public FRM_Login(FRM_MenuPrincipal frm_menuPrincipal) {
        initComponents();
        
        controladorLogin=new Controlador_FRM_Login(this,frm_menuPrincipal);
        gUI_Login1.agregarEventos(controladorLogin);
    }
    public void hacerLogin()
    {
        
        setVisible(true);    
    }
    public void noHacerLogin()
    {
        
        setVisible(false);
    }
    public String devolverNombreUsuario()
    {
        return this.gUI_Login1.devolverNombreUsuario();
    }
    public String devolverContraseña()
    {
        return this.gUI_Login1.devolverContraseña();
    }
    public void mensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Login1 = new Vista.GUI_Login();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gUI_Login1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                gUI_Login1ComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gUI_Login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gUI_Login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gUI_Login1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_gUI_Login1ComponentHidden
        // TODO add your handling code here:
//        controladorLogin.crearArchivo();
    }//GEN-LAST:event_gUI_Login1ComponentHidden

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Login gUI_Login1;
    // End of variables declaration//GEN-END:variables
}
