/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_ModuloMantenimientoUsuarios;
import Modelo.ArchivosUsuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Moon
 */
public class FRM_ModuloMantenimientoUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form FRM_ModuloMantenimientoUsuarios
     */
    Controlador_FRM_ModuloMantenimientoUsuarios controladorUsuarios;
    
    public FRM_ModuloMantenimientoUsuarios(ArchivosUsuarios archivos,FRM_MenuPrincipal frm_menuPrincipal) {
        
        controladorUsuarios=new Controlador_FRM_ModuloMantenimientoUsuarios(this,archivos,frm_menuPrincipal);
        initComponents();
        gUI_Botones1.agregarEventos(controladorUsuarios);
        
        
    }
     public String[] devolverInformacion()
    {
        return this.gUI_ModuloMantenimientoUsuarios1.devolverInformacion();
    }
    public String devolverNombreUsuario()
    {
        return this.gUI_ModuloMantenimientoUsuarios1.devolverNombreUsuario();
    
    }
    public void mensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.gUI_ModuloMantenimientoUsuarios1.mostrarInformacion(arreglo);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_ModuloMantenimientoUsuarios1 = new Vista.GUI_ModuloMantenimientoUsuarios();
        gUI_Botones1 = new Vista.GUI_Botones();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gUI_ModuloMantenimientoUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_ModuloMantenimientoUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        controladorUsuarios.crearArchivo();
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_ModuloMantenimientoUsuarios gUI_ModuloMantenimientoUsuarios1;
    // End of variables declaration//GEN-END:variables
}
